/**
 * RBAC Role Definitions — Enterprise v2.2
 * 
 * 4 vaste rollen. Niet wijzigbaar via UI.
 * SUPER_ADMIN heeft wildcard (*) toegang.
 */

import { PERMISSIONS, WILDCARD } from './permissionRegistry';

export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  HR_ADMIN: 'HR_ADMIN',
  PLANNER: 'PLANNER',
  EMPLOYEE: 'EMPLOYEE',
};

export const ROLE_LABELS = {
  [ROLES.SUPER_ADMIN]: 'Super Admin',
  [ROLES.HR_ADMIN]: 'HR Admin',
  [ROLES.PLANNER]: 'Planner',
  [ROLES.EMPLOYEE]: 'Medewerker',
};

/**
 * Permission mapping per rol.
 * SUPER_ADMIN krijgt wildcard — alle permissions.
 */
export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [WILDCARD],

  [ROLES.HR_ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ONBOARDING_MANAGE,
    PERMISSIONS.EMPLOYEES_MANAGE,
    PERMISSIONS.CONTRACTS_MANAGE,
    PERMISSIONS.DOCUMENTS_MANAGE,
    PERMISSIONS.ID_SHARE,
    PERMISSIONS.MAIL_SEND,
    PERMISSIONS.PLANNING_READ,
    PERMISSIONS.MOBILE_READWRITE,
    PERMISSIONS.AUDIT_READ,
  ],

  [ROLES.PLANNER]: [
    PERMISSIONS.PLANNING_MANAGE,
    PERMISSIONS.CUSTOMERS_MANAGE,
    PERMISSIONS.PROJECTS_MANAGE,
    PERMISSIONS.ACTIVITIES_MANAGE,
    PERMISSIONS.CHARTERS_MANAGE,
    PERMISSIONS.KPI_VIEW,
  ],

  [ROLES.EMPLOYEE]: [
    PERMISSIONS.MOBILE_OWN,
    PERMISSIONS.PLANNING_OWN_READ,
    PERMISSIONS.CONTRACT_OWN_SIGN,
    PERMISSIONS.SERVICES_OWN_READ,
  ],
};

/**
 * Haal permissions op voor een rol.
 * Onbekende rollen krijgen EMPLOYEE permissions.
 */
export function getPermissionsForRole(role) {
  return ROLE_PERMISSIONS[role] || ROLE_PERMISSIONS[ROLES.EMPLOYEE];
}