import React, { useState, useMemo, useCallback, useEffect } from "react";
import { Plus, Save, ChevronLeft, AlertTriangle } from "lucide-react";
import { toast } from "sonner";
import AutoSaveIndicator from "@/components/mobile/AutoSaveIndicator";
import { validateDienstRegels, findOverlaps, timeToMinutes } from "@/components/utils/mobile/dienstRegelValidation";
import DienstRegelRow from "@/components/mobile/dienstregels/DienstRegelRow";
import DienstRegelDrawer from "@/components/mobile/dienstregels/DienstRegelDrawer";
import DeleteConfirmDialog from "@/components/mobile/dienstregels/DeleteConfirmDialog";

const EMPTY_TRIP = {
  start_time: "", end_time: "", departure_location: "Standplaats",
  vehicle_id: "", damage_occurred: "Nee",
  start_km: "", end_km: "", fuel_liters: "", adblue_liters: "",
  fuel_km: "", charging_kwh: "", customer_id: "", route_name: "",
  planned_stops: "", notes: ""
};

const EMPTY_STANDPLAATS = {
  start_time: "", end_time: "", customer_id: "", project_id: "",
  activity_id: "", custom_activity: "", notes: ""
};

function generateId() {
  return crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;
}

function getPrefillStartTime(dienstRegels, dienstStartTime) {
  // 1. Regels met geldige end_time → pak de max
  const withEnd = dienstRegels
    .map(r => ({ ...r, _endMin: timeToMinutes(r.end_time) }))
    .filter(r => r._endMin !== null);

  if (withEnd.length > 0) {
    const maxEnd = Math.max(...withEnd.map(r => r._endMin));
    return { start_time: fmtMin(maxEnd), end_time: "" };
  }

  // 2. Open activiteit (heeft start_time maar geen end_time)
  const open = dienstRegels
    .map(r => ({ ...r, _startMin: timeToMinutes(r.start_time) }))
    .filter(r => r._startMin !== null && timeToMinutes(r.end_time) === null);

  if (open.length > 0) {
    const maxStart = Math.max(...open.map(r => r._startMin));
    return { start_time: fmtMin(maxStart), end_time: "" };
  }

  // 3. Fallback: dienst starttijd
  const fallback = timeToMinutes(dienstStartTime);
  if (fallback !== null) return { start_time: fmtMin(fallback), end_time: "" };

  return { start_time: "", end_time: "" };
}

function fmtMin(m) {
  const h = Math.floor(m / 60) % 24;
  const mm = m % 60;
  return `${String(h).padStart(2, '0')}:${String(mm).padStart(2, '0')}`;
}

export default function DienstRegelsTab({
  dienstRegels, setDienstRegels,
  vehicles, customers, routes, tiModelRoutes, projects, activiteiten,
  progressStep, lastSavedAt, isSaving, isSubmitting,
  storageKey, onSaveDraft, setActiveTab,
  formData,
  postNLAuto = false, postNLOpenDrawer = false, setPostNLOpenDrawer,
  hasSubmittedActivities = false,
  onSaveAndGoHome, onCloseOpenRitToDienst
}) {
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [editingRegel, setEditingRegel] = useState(null);
  const [isNewRegel, setIsNewRegel] = useState(false);
  const [addMenuOpen, setAddMenuOpen] = useState(false);
  const [deleteTarget, setDeleteTarget] = useState(null);

  // Auto-open drawer for PostNL flow
  useEffect(() => {
    if (postNLOpenDrawer && dienstRegels.length > 0 && !drawerOpen) {
      const autoRit = dienstRegels.find(r => r.autoGenerated);
      if (autoRit) {
        setEditingRegel(autoRit);
        setIsNewRegel(true);
        setDrawerOpen(true);
      }
      setPostNLOpenDrawer?.(false);
    }
  }, [postNLOpenDrawer, dienstRegels]);

  const isSingleDay = !formData?.end_date || formData.end_date === formData.date;
  const validation = useMemo(() =>
    validateDienstRegels(dienstRegels, formData?.start_time, formData?.end_time, isSingleDay),
    [dienstRegels, formData?.start_time, formData?.end_time, isSingleDay]
  );
  const hasValidationErrors = validation.hasOverlap || validation.hasGap;

  const overlapSet = useMemo(() => {
    const set = new Set();
    findOverlaps(dienstRegels).forEach(({ i, j }) => {
      if (dienstRegels[i]) set.add(dienstRegels[i].id);
      if (dienstRegels[j]) set.add(dienstRegels[j].id);
    });
    return set;
  }, [dienstRegels]);

  const sorted = useMemo(() =>
    [...dienstRegels].sort((a, b) => (timeToMinutes(a.start_time) ?? 9999) - (timeToMinutes(b.start_time) ?? 9999)),
    [dienstRegels]
  );

  const addRegel = (type) => {
    const prefill = getPrefillStartTime(dienstRegels, formData?.start_time);
    const newRegel = { id: generateId(), type, ...(type === "rit" ? { ...EMPTY_TRIP } : { ...EMPTY_STANDPLAATS }), ...prefill };
    setDienstRegels(prev => [...prev, newRegel]);
    setEditingRegel(newRegel);
    setIsNewRegel(true);
    setDrawerOpen(true);
    setAddMenuOpen(false);
  };

  const handleTap = (regel) => { setEditingRegel(regel); setIsNewRegel(false); setDrawerOpen(true); };
  const handleSaveRegel = (updatedRegel) => { setDienstRegels(prev => prev.map(r => r.id === updatedRegel.id ? updatedRegel : r)); };

  const requestDelete = useCallback((id) => setDeleteTarget(id), []);
  const confirmDelete = useCallback(async () => {
    if (!deleteTarget) return;
    const regel = dienstRegels.find(r => r.id === deleteTarget);
    if (regel?._existingId && regel.type === "standplaats") {
      try { await (await import("@/api/base44Client")).base44.entities.StandplaatsWerk.delete(regel._existingId); } catch {}
    }
    setDienstRegels(prev => prev.filter(r => r.id !== deleteTarget));
    setDeleteTarget(null);
  }, [deleteTarget, dienstRegels, setDienstRegels]);

  return (
    <div className="flex flex-col">
      {/* Nav bar */}
      <div className="flex items-center justify-between mb-3">
        <button type="button" onClick={() => setActiveTab("dienst")} className="flex items-center gap-1 text-[13px] text-blue-600 font-medium">
          <ChevronLeft className="w-4 h-4" /> Diensttijd
        </button>
        <AutoSaveIndicator lastSavedAt={lastSavedAt} isSaving={isSaving} />
      </div>

      {/* Submitted banner */}
      {hasSubmittedActivities && (
        <div className="px-2.5 py-2.5 bg-blue-50 border-l-2 border-blue-400 rounded-r-lg mb-2">
          <p className="text-[12px] text-blue-700 font-semibold">✓ Al ingediend</p>
          <p className="text-[10px] text-blue-600 mt-0.5">De activiteiten voor deze datum zijn al ingediend. Wijzigingen zijn niet mogelijk.</p>
        </div>
      )}

      {/* Validation banner */}
      {hasValidationErrors && !hasSubmittedActivities && (
        <div className="px-2.5 py-2 bg-red-50 border-l-2 border-red-400 rounded-r-lg mb-2">
          <div className="flex items-center gap-1.5 text-red-700 font-semibold text-[11px]">
            <AlertTriangle className="w-3.5 h-3.5" />
            <span>Corrigeer:</span>
          </div>
          {[...validation.overlaps, ...validation.gaps].map((msg, i) => (
            <p key={i} className="text-[10px] text-red-600 ml-5">• {msg}</p>
          ))}
        </div>
      )}

      {/* Title */}
      <div className="flex items-center justify-between mb-2">
        <h3 className="text-[15px] font-semibold text-slate-900">Dienstregels</h3>
        <span className="text-[11px] text-slate-400">{dienstRegels.length} regel{dienstRegels.length !== 1 ? 's' : ''}</span>
      </div>

      {/* Content — edge-to-edge rows */}
      <div className="-mx-4">
        {sorted.length === 0 ? (
          <div className="text-center py-10 text-slate-400">
            <p className="text-[13px]">Nog geen regels</p>
            <p className="text-[11px] mt-1">Tik hieronder om toe te voegen</p>
          </div>
        ) : (
          <div className="divide-y divide-slate-100">
            {sorted.map((regel) => (
              <DienstRegelRow
                key={regel.id}
                regel={regel}
                customers={customers}
                hasOverlap={overlapSet.has(regel.id)}
                onTap={() => !hasSubmittedActivities && handleTap(regel)}
                onDelete={hasSubmittedActivities ? undefined : () => requestDelete(regel.id)}
              />
            ))}
          </div>
        )}
      </div>

      {/* Bottom actions */}
      <div className="bg-white pt-2 pb-1 -mx-4 px-4 border-t border-slate-100 mt-2 space-y-1.5">
        {hasSubmittedActivities ? (
          <button type="button" onClick={() => setActiveTab("dienst")}
            className="w-full h-[36px] rounded-lg bg-slate-100 text-slate-500 text-[13px] font-medium flex items-center justify-center">
            ← Terug naar Diensttijd
          </button>
        ) : postNLAuto && dienstRegels.length > 0 ? (
          <>
            {/* Secondary: add more rules — small link, not dominant */}
            <button type="button"
              onClick={() => setAddMenuOpen(prev => !prev)}
              className="w-full text-center text-[12px] text-slate-500 font-medium py-1.5">
              <Plus className="w-3 h-3 inline mr-1" />Extra regel toevoegen
            </button>
            {addMenuOpen && (
              <div className="bg-white rounded-xl border shadow-lg p-1.5">
                <button type="button" onClick={() => addRegel("rit")}
                  className="w-full flex items-center gap-3 px-3 py-2.5 rounded-lg hover:bg-blue-50 active:bg-blue-100 text-left">
                  <span className="text-lg">🚛</span>
                  <div>
                    <p className="text-[13px] font-medium text-slate-900">Rit toevoegen</p>
                    <p className="text-[10px] text-slate-500">Transport / bezorging</p>
                  </div>
                </button>
                <button type="button" onClick={() => addRegel("standplaats")}
                  className="w-full flex items-center gap-3 px-3 py-2.5 rounded-lg hover:bg-amber-50 active:bg-amber-100 text-left">
                  <span className="text-lg">📦</span>
                  <div>
                    <p className="text-[13px] font-medium text-slate-900">Standplaats toevoegen</p>
                    <p className="text-[10px] text-slate-500">Werk op locatie</p>
                  </div>
                </button>
              </div>
            )}
          </>
        ) : (
          <>
            {/* Default: "Regel toevoegen" — compact add menu */}
            <div className="relative">
              {addMenuOpen && (
                <div className="absolute bottom-full left-0 right-0 mb-1 bg-white rounded-xl border shadow-lg p-1.5 z-10">
                  <button type="button" onClick={() => addRegel("rit")}
                    className="w-full flex items-center gap-3 px-3 py-2.5 rounded-lg hover:bg-blue-50 active:bg-blue-100 text-left">
                    <span className="text-lg">🚛</span>
                    <div>
                      <p className="text-[13px] font-medium text-slate-900">Rit toevoegen</p>
                      <p className="text-[10px] text-slate-500">Transport / bezorging</p>
                    </div>
                  </button>
                  <button type="button" onClick={() => addRegel("standplaats")}
                    className="w-full flex items-center gap-3 px-3 py-2.5 rounded-lg hover:bg-amber-50 active:bg-amber-100 text-left">
                    <span className="text-lg">📦</span>
                    <div>
                      <p className="text-[13px] font-medium text-slate-900">Standplaats toevoegen</p>
                      <p className="text-[10px] text-slate-500">Werk op locatie</p>
                    </div>
                  </button>
                </div>
              )}
              <button
                type="button"
                onClick={() => setAddMenuOpen(prev => !prev)}
                className="w-full h-[36px] rounded-lg bg-blue-600 text-white text-[13px] font-medium flex items-center justify-center gap-1.5 active:bg-blue-700"
              >
                <Plus className="w-3.5 h-3.5" /> Regel toevoegen
              </button>
            </div>

            {dienstRegels.length > 0 && (
              <div className="flex items-center justify-between">
                <button type="button" onClick={onSaveDraft} disabled={isSubmitting}
                  className="text-[12px] text-emerald-700 font-medium py-1">
                  <Save className="w-3 h-3 inline mr-1" />Opslaan
                </button>
                <button type="button"
                  onClick={async () => { await onSaveDraft(); setActiveTab("dienst"); }}
                  disabled={isSubmitting || hasValidationErrors}
                  className="text-[12px] text-blue-600 font-medium py-1 disabled:text-slate-400">
                  Volgende → Eindtijd
                </button>
              </div>
            )}
          </>
        )}
      </div>

      {/* Fullscreen drawer */}
      <DienstRegelDrawer
        open={drawerOpen} onOpenChange={setDrawerOpen}
        regel={editingRegel} allRegels={dienstRegels}
        onSave={handleSaveRegel} onDelete={requestDelete}
        vehicles={vehicles} customers={customers}
        routes={routes} tiModelRoutes={tiModelRoutes}
        projects={projects} activiteiten={activiteiten}
        dienstStartTime={formData?.start_time}
        dienstEndTime={formData?.end_time}
        isNewRegel={isNewRegel}
        onSaveAndGoHome={onSaveAndGoHome}
        onCloseOpenRitToDienst={onCloseOpenRitToDienst}
      />

      <DeleteConfirmDialog
        open={!!deleteTarget}
        onOpenChange={(open) => { if (!open) setDeleteTarget(null); }}
        onConfirm={confirmDelete}
      />
    </div>
  );
}